excludes:
  - \.editorconfig
  - \.env
  - \.gitignore
  - .*lock
  - \.git/.*
  - README.*
  - LICENSE.*
  - .*\.(md|rst|txt)
  - .*\.(png|jpg|jpeg|gif|svg|ico)
  - .*\.(ttf|woff|woff2|eot)
  - .*\.(zip|tar|gz|tgz|rar|7z|bz2|exe|msi)
  - .*\.(json|xml|csv|tsv|log|ini|conf|cfg|toml|env)
  - go.(mod|sum)
  - coverage.out
authors:
  - name: Breu, Inc.
    email: info@breu.io
licenses:
  - files: any
    authors:
    - name: Breu, Inc.
      email: info@breu.io
    ident: Unlicense
    template: |
      Copyright © [year], [name of author]. All rights reserved.


      This software is made available by Breu, Inc., under the terms of the
      BREU COMMUNITY LICENSE AGREEMENT, Version 1.0, found at https://www.breu.io/license/community.
      BY INSTALLATING, DOWNLOADING, ACCESSING, USING OR DISTRUBTING ANY OF THE
      SOFTWARE, YOU AGREE TO THE TERMS OF THE LICENSE AGREEMENT.


      The above copyright notice and the subsequent license agreement shall be
      included in all copies or substantial portions of the software.


      Breu, Inc. HEREBY DISCLAIMS ANY AND ALL WARRANTIES AND CONDITIONS, EXPRESS,
      IMPLIED, STATUTORY, OR OTHERWISE, AND SPECIFICALLY DISCLAIMS ANY WARRANTY OF
      MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE, WITH RESPECT TO THE
      SOFTWARE.


      Breu, Inc. SHALL NOT BE LIABLE FOR ANY DAMAGES OF ANY KIND, INCLUDING BUT NOT
      LIMITED TO, LOST PROFITS OR ANY CONSEQUENTIAL, SPECIAL, INCIDENTAL, INDIRECT,
      OR DIRECT DAMAGES, HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, ARISING
      OUT OF THIS AGREEMENT. THE FOREGOING SHALL APPLY TO THE EXTENT PERMITTED BY
      APPLICABLE LAW.
comments:
  - extensions:
      - ts
      - js
      - rs
      - go
      - cue
    columns: 120
    commenter:
      type: line
      comment_char: "//"
      trailing_lines: 1

  - extensions:
      - css
      - cpp
      - c
    columns: 120
    commenter:
      type: block
      start_block_char: "/*\n"
      end_block_char: "*/"
      per_line_char: "*"
      trailing_lines: 1

  - extension: html
    columns: 120
    commenter:
      type: block
      start_block_char: "<!--\n"
      end_block_char: "-->"

  - extensions:
      - el
      - lisp
    columns: 120
    commenter:
      type: line
      comment_char: ";;;"
      trailing_lines: 1

  - extension:
      - py
      - yaml
      - yml
      - toml
    columns: 120
    commenter:
      type: line
      comment_char: "#"
      trailing_lines: 1

  - extension:
      - cql
      - sql
    columns: 120
    commenter:
      type: line
      comment_char: "--"
      trailing_lines: 1
