# Regexes which if matched by a file path will always be excluded from
# getting a license header
excludes:
  - \.editorconfig
  - \.env
  - \.gitignore
  - .*lock
  - \.git/.*
  - \.licensure\.yml
  - README.*
  - LICENSE.*
  - .*\.(md|rst|txt)
  - .*\.(png|jpg|jpeg|gif|svg|ico)
  - .*\.(ttf|woff|woff2|eot)
  - .*\.(zip|tar|gz|tgz|rar|7z|bz2|exe|msi)
  - .*\.(json|xml|csv|tsv|log|ini|conf|cfg|toml|env)
  - go.(mod|sum)
  - coverage.out
authors:
  - name: Breu Inc.
    email: info@breu.io
licenses:
  - files: any
    authors:
    - name: Breu Inc.
      email: info@breu.io
    ident: Unlicense
    template: |
      Copyright © [year], [name of author]. All rights reserved.


      This software is made available by Breu, Inc., under the terms of the

      Breu Community License Agreement, version 1.0, located at https://www.breu.io/license/community. 

      By installating, download, accessing, using or distrubting any of the software
      
      you agree to the terms of the license agreement.


      The above copyright notice and this permission notice shall be included in

      all copies or substantial portions of the Software.


      Breu, Inc. HEREBY DISCLAIMS ANY AND ALL WARRANTIES AND CONDITIONS, EXPRESS,

      IMPLIED, STATUTORY, OR OTHERWISE, AND SPECIFICALLY DISCLAIMS ANY WARRANTY OF

      MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE, WITH RESPECT TO THE

      SOFTWARE.


      Breu, Inc. SHALL NOT BE LIABLE FOR ANY DAMAGES OF ANY KIND, INCLUDING BUT NOT

      LIMITED TO, LOST PROFITS OR ANY CONSEQUENTIAL, SPECIAL, INCIDENTAL, INDIRECT,

      OR DIRECT DAMAGES, HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, ARISING

      OUT OF THIS AGREEMENT. THE FOREGOING SHALL APPLY TO THE EXTENT PERMITTED BY 

      APPLICABLE LAW.

comments:
  - extensions:
      - ts
      - js
      - rs
      - go
      - cue
    commenter:
      type: line
      comment_char: "//"
      trailing_lines: 1
 
  - extensions:
      - css
      - cpp
      - c
    commenter:
      type: block
      start_block_char: "/*\n"
      end_block_char: "*/"
      per_line_char: "*"
      trailing_lines: 1

  - extension: html
    commenter:
      type: block
      start_block_char: "<!--\n"
      end_block_char: "-->"

  - extensions:
      - el
      - lisp
    commenter:
      type: line
      comment_char: ";;;"
      trailing_lines: 1

  - extension:
      - py
      - yaml
      - yml
    commenter:
      type: line
      comment_char: "#"
      trailing_lines: 1

  - extension:
      - cql
      - sql
    commenter:
      type: line
      comment_char: "--"
      trailing_lines: 1
    
