# Regexes which if matched by a file path will always be excluded from
# getting a license header
excludes:
  - \.editorconfig
  - \.env
  - \.gitignore
  - .*lock
  - \.git/.*
  - \.licensure\.yml
  - README.*
  - LICENSE.*
  - .*\.(md|rst|txt)
  - .*\.(png|jpg|jpeg|gif|svg|ico)
  - .*\.(ttf|woff|woff2|eot)
  - .*\.(zip|tar|gz|tgz|rar|7z|bz2|exe|msi)
  - .*\.(json|xml|csv|tsv|log|ini|conf|cfg|toml|env)
  - go.(mod|sum)
authors:
  - name: Breu Inc.
    email: info@breu.io
licenses:
  - files: any
    authors:
    - name: Breu Inc.
      email: info@breu.io
    ident: Unlicense
    template: |
      Copyright © [year], [name of author]. All rights reserved.


      This software is made available by Breu, Inc., under the terms of the

      Breu Community License Agreement, version 1.0, located at https://www.breu.io/license/community. 

      By installating, download, accessing, using or distrubting any of the software
      
      you agree to the terms of the license agreement.


      The above copyright notice and this permission notice shall be included in

      all copies or substantial portions of the Software.


      THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR

      IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,

      FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE

      AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER

      LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,

      OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN

      THE SOFTWARE.

comments:
  - extensions:
      - ts
      - js
      - rs
      - go
      - cue
    commenter:
      type: line
      comment_char: "//"
      trailing_lines: 1
 
  - extensions:
      - css
      - cpp
      - c
    commenter:
      type: block
      start_block_char: "/*\n"
      end_block_char: "*/"
      per_line_char: "*"
      trailing_lines: 1

  - extension: html
    commenter:
      type: block
      start_block_char: "<!--\n"
      end_block_char: "-->"

  - extensions:
      - el
      - lisp
    commenter:
      type: line
      comment_char: ";;;"
      trailing_lines: 1

  - extension:
      - py
      - yaml
      - yml
    commenter:
      type: line
      comment_char: "#"
      trailing_lines: 1

  - extension:
      - cql
      - sql
    commenter:
      type: line
      comment_char: "--"
      trailing_lines: 1
    
