# Copyright © 2023, Breu, Inc. <info@breu.io>. All rights reserved.
#
# This software is made available by Breu, Inc., under the terms of the BREU COMMUNITY LICENSE AGREEMENT, Version 1.0,
# found at https://www.breu.io/license/community. BY INSTALLING, DOWNLOADING, ACCESSING, USING OR DISTRIBUTING ANY OF
# THE SOFTWARE, YOU AGREE TO THE TERMS OF THE LICENSE AGREEMENT.
#
# The above copyright notice and the subsequent license agreement shall be included in all copies or substantial
# portions of the software.
#
# Breu, Inc. HEREBY DISCLAIMS ANY AND ALL WARRANTIES AND CONDITIONS, EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, AND
# SPECIFICALLY DISCLAIMS ANY WARRANTY OF MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE, WITH RESPECT TO THE
# SOFTWARE.
#
# Breu, Inc. SHALL NOT BE LIABLE FOR ANY DAMAGES OF ANY KIND, INCLUDING BUT NOT LIMITED TO, LOST PROFITS OR ANY
# CONSEQUENTIAL, SPECIAL, INCIDENTAL, INDIRECT, OR DIRECT DAMAGES, HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
# ARISING OUT OF THIS AGREEMENT. THE FOREGOING SHALL APPLY TO THE EXTENT PERMITTED BY APPLICABLE LAW.

version: '3.9'

services:
  # common
  database:
    container_name: database
    image: cassandra:4
    ports:
      - '9042:9042'
    environment:
      - CASSNDRA_CLUSTER_NAME=ctrlplane
      - JVM_EXTRA_OPTS=-Dcassandra.skip_wait_for_gossip_to_settle=0
    volumes:
      - db-data:/var/lib/cassandra
      - ./deploy/cassandra/cassandra.yaml:/etc/cassandra/cassandra.yaml
    networks:
      - ctrlplane

  database-init:
    container_name: ctrlplane-db-init
    image: cassandra:4
    depends_on:
      - database
    volumes:
      - ./deploy/cassandra/keyspace.cql:/keyspace.cql
    command: /bin/bash -c "sleep 20 && echo loading database keyspace && cqlsh database -f /keyspace.cql"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

    networks:
      - ctrlplane

  mailslurper:
    container_name: mailslurper
    image: oryd/mailslurper:latest-smtps
    ports:
      - '4436:4436'
      - '4437:4437'
    networks:
      - ctrlplane

  # nats.io
  event-stream:
    container_name: event-stream
    image: nats:2.8.4
    ports:
      - '4222:4222'
    command: --cluster_name ctrlplane
    networks:
      - ctrlplane

  # temporal.io
  temporal:
    container_name: temporal
    depends_on:
      - database
    environment:
      - CASSANDRA_SEEDS=database
      - DYNAMIC_CONFIG_FILE_PATH=config/dynamicconfig/development-cass.yaml
    image: temporalio/auto-setup:1.20.0
    ports:
      - '7233:7233'
    volumes:
      - ./deploy/temporal/dynamicconfig/:/etc/temporal/config/dynamicconfig/
    networks:
      - ctrlplane

  temporal-admin-tools:
    container_name: temporal-admin-tools
    depends_on:
      - temporal
    environment:
      - TEMPORAL_CLI_ADDRESS=temporal:7233
    image: temporalio/admin-tools:1.20.0
    stdin_open: true
    tty: true
    networks:
      - ctrlplane

  temporal-ui:
    container_name: temporal-ui
    depends_on:
      - temporal
    environment:
      TEMPORAL_ADDRESS: temporal:7233
      TEMPORAL_CORS_ORIGINS: http://localhost:3000
    image: temporalio/ui:2.10.3
    ports:
      - 8080:8080
    networks:
      - ctrlplane

  # ctrlplane.ai
  ctrlplane-job-migrate:
    profiles:
      - full
      - api
      - mothership
      - migrate
    container_name: ctrlplane-job-migrate
    image: cosmtrek/air:v1.42.0
    environment:
      SERVICE_NAME: job::migrate
      CASSANDRA_MIGRATION_SOURCE_URL: file:///migrate/internal/db/migrations
    env_file:
      - ./.env
    volumes:
      - ./deploy/air/migrate.toml:/migrate/.air.toml
      - ./:/migrate/
      - job-migrate-go-pkg-mod:/go/pkg/mod
      - job-migrate-build-cache:/root/.cache/go-build
    working_dir: /migrate
    networks:
      - ctrlplane

  ctrlplane-api:
    profiles:
      - full
      - api
    container_name: ctrlplane-api
    image: cosmtrek/air:v1.42.0
    environment:
      SERVICE_NAME: web::api
      DEBUG: true
    env_file:
      - ./.env
    ports:
      - '8000:8000'
    volumes:
      - ./deploy/air/api.toml:/api/.air.toml
      - ./:/api/
      - api-go-pkg-mod:/go/pkg/mod
      - api-build-cache:/root/.cache/go-build
    working_dir: /api
    networks:
      - ctrlplane

  ctrlplane-worker--mothership:
    container_name: ctrlplane-worker--mothership
    profiles:
      - full
      - mothership
    image: cosmtrek/air:v1.42.0
    environment:
      SERVICE_NAME: worker::mothership
      DEBUG: true
    env_file:
      - ./.env
    volumes:
      - ./deploy/air/mothership.toml:/mothership/.air.toml
      - ./:/mothership/
      - worker-mothership-go-pkg-mod:/go/pkg/mod
      - worker-mothership-build-cache:/root/.cache/go-build
    working_dir: /mothership
    networks:
      - ctrlplane

networks:
  ctrlplane: {}

volumes:
  temporal-pg-data: {}
  db-data: {}
  api-go-pkg-mod: {}
  api-build-cache: {}
  worker-mothership-go-pkg-mod: {}
  worker-mothership-build-cache: {}
  job-migrate-go-pkg-mod: {}
  job-migrate-build-cache: {}
