services:
  # common
  database:
    container_name: database
    image: scylladb/scylla:6.1.1
    ports:
      - "9042:9042"
    volumes:
      - db-data:/var/lib/scylla
    command: --smp 1 --skip-wait-for-gossip-to-settle 0
    networks:
      - ctrlplane

  database-init:
    container_name: ctrlplane-db-init
    image: scylladb/scylla-cqlsh:v6.0.20
    depends_on:
      - database
    volumes:
      - ./deploy/cassandra/keyspace.cql:/keyspace.cql
    command: database -f /keyspace.cql
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 10
        window: 120s
    networks:
      - ctrlplane

  # temporal.io
  temporal:
    container_name: temporal
    depends_on:
      - database
    environment:
      - CASSANDRA_SEEDS=database
      - DYNAMIC_CONFIG_FILE_PATH=config/dynamicconfig/development-cass.yaml
    image: temporalio/auto-setup:1.22.5
    ports:
      - "7233:7233"
    volumes:
      - ./deploy/temporal/dynamicconfig/:/etc/temporal/config/dynamicconfig/
    networks:
      - ctrlplane

  temporal-admin-tools:
    container_name: temporal-admin-tools
    depends_on:
      - temporal
    environment:
      - TEMPORAL_CLI_ADDRESS=temporal:7233
    image: temporalio/admin-tools:1.22.5
    stdin_open: true
    tty: true
    networks:
      - ctrlplane

  temporal-ui:
    container_name: temporal-ui
    depends_on:
      - temporal
    environment:
      TEMPORAL_ADDRESS: temporal:7233
      TEMPORAL_CORS_ORIGINS: http://localhost:3000
    image: temporalio/ui:2.29.0
    ports:
      - 8080:8080
    networks:
      - ctrlplane

  # quantm.io
  ctrlplane-job-migrate:
    profiles:
      - full
      - api
      - mothership
      - migrate
    container_name: ctrlplane-job-migrate
    image: cosmtrek/air:v1.52.3
    environment:
      GOTOOLCHAIN: auto
      SERVICE_NAME: migrate
      CASSANDRA_MIGRATION_SOURCE_URL: file:///migrate/internal/db/migrations
    env_file:
      - ./.env
    volumes:
      - ./deploy/air/migrate.toml:/migrate/.air.toml
      - ./:/migrate/
      - job-migrate-go-pkg-mod:/go/pkg/mod
      - job-migrate-build-cache:/root/.cache/go-build
    working_dir: /migrate
    networks:
      - ctrlplane

  ctrlplane-api:
    profiles:
      - full
      - api
    container_name: ctrlplane-api
    image: cosmtrek/air:v1.52.3
    environment:
      GOTOOLCHAIN: auto
      SERVICE_NAME: api
    env_file:
      - ./.env
    ports:
      - "8000:8000"
    volumes:
      - ./deploy/air/api.toml:/api/.air.toml
      - ./:/api/
      - api-go-pkg-mod:/go/pkg/mod
      - api-build-cache:/root/.cache/go-build
    working_dir: /api
    networks:
      - ctrlplane

  ctrlplane-worker--mothership:
    container_name: ctrlplane-worker--mothership
    profiles:
      - mothership
      - full
    image: cosmtrek/air:v1.52.3
    environment:
      GOTOOLCHAIN: auto
      SERVICE_NAME: mothership
      LOG_SKIPPER: 2
    env_file:
      - ./.env
    volumes:
      - ./deploy/air/mothership.toml:/mothership/.air.toml
      - ./:/mothership/
      - worker-mothership-go-pkg-mod:/go/pkg/mod
      - worker-mothership-build-cache:/root/.cache/go-build
    working_dir: /mothership
    networks:
      - ctrlplane

  prod-api:
    container_name: prod-api
    profiles:
      - prod
    build:
      context: .
      dockerfile: Dockerfile
      target: api
    environment:
      TEMPORAL_HOST: temporal
      CASSANDRA_HOSTS: database
    env_file:
      - ./.env
    ports:
      - "8000:8000"
    volumes:
      - api-go-pkg-mod:/root/go/pkg/mod
      - api-build-cache:/root/.cache/go-build
    networks:
      - ctrlplane

  prod-worker-mothership:
    container_name: prod-worker-mothership
    profiles:
      - prod
    build:
      context: .
      dockerfile: Dockerfile
      target: mothership
    environment:
      TEMPORAL_HOST: temporal
      CASSANDRA_HOSTS: database
    env_file:
      - ./.env
    volumes:
      - worker-mothership-go-pkg-mod:/root/go/pkg/mod
      - worker-mothership-build-cache:/root/.cache/go-build
    networks:
      - ctrlplane


networks:
  ctrlplane: {}

volumes:
  db-data: {}
  api-go-pkg-mod: {}
  api-build-cache: {}
  worker-mothership-go-pkg-mod: {}
  worker-mothership-build-cache: {}
  job-migrate-go-pkg-mod: {}
  job-migrate-build-cache: {}
