version: '3.6'
services:
  cassandra:
    container_name: cassandra
    image: cassandra:4
    ports:
      - '9042:9042'
    environment:
      - CASSNDRA_CLUSTER_NAME=ctrlplane
    volumes:
      - ctrlplane-db-data:/var/lib/cassandra

  mailslurper:
    container_name: mailslurper
    image: oryd/mailslurper:latest-smtps
    ports:
      - '4436:4436'
      - '4437:4437'

  event-stream:
    container_name: event-stream
    image: nats:2.8.4
    ports:
      - 4222:4222
    command: --cluster_name ctrlplane 


  # Temporal - https://temporal.io
  temporal-db:
    container_name: temporal-db
    image: postgres:14
    environment:
      POSTGRES_PASSWORD: ${TEMPORAL_DB_PASS}
      POSTGRES_USER: ${TEMPORAL_DB_USER}
    ports:
      - 5432:5432
    volumes:
      - temporal-pg-data:/var/lib/postgresql/data

  temporal:
    container_name: temporal
    depends_on:
      - temporal-db
    environment:
      DB: postgresql
      DB_PORT: 5432
      POSTGRES_USER: ${TEMPORAL_DB_USER}
      POSTGRES_PWD: ${TEMPORAL_DB_PASS}
      POSTGRES_SEEDS: temporal-db
      DYNAMIC_CONFIG_FILE_PATH: config/dynamicconfig/dev.yaml
    image: temporalio/auto-setup:1.16.2
    ports:
      - 7233:7233
    volumes:
      - ./deploy/temporal/dynamicconfig/:/etc/temporal/config/dynamicconfig/

  temporal-admin-tools:
    container_name: temporal-admin-tools
    depends_on:
      - temporal
    environment:
      - TEMPORAL_CLI_ADDRESS=temporal:7233
    image: temporalio/admin-tools:1.16.2
    stdin_open: true
    tty: true

  temporal-ui:
    container_name: temporal-ui
    depends_on:
      - temporal
    environment:
      TEMPORAL_ADDRESS: temporal:7233
      TEMPORAL_CORS_ORIGINS: http://localhost:3000
    image: temporalio/ui:2.0.0
    ports:
      - 8080:8080

  ctrlplane-api:
    container_name: ctrlplane-api
    image: cosmtrek/air
    environment:
      SERVICE_NAME: web::api
      CASSANDRA_MIGRATION_SOURCE_URL: file:///api/internal/db/migrations
    env_file:
      - ./.env
    ports:
      - 8000:8000
    volumes:
      - ./deploy/air/api.toml:/api/.air.toml
      - ./:/api/
      - ctrlplane-api-go-pkg-mod:/root/go/pkg/mod # TODO: not working, fix this
      - ctrlplane-api-build-cache:/root/.cache/go-build # TODO: not working, fix this
    working_dir: /api

  ctrlplane-worker:
    container_name: ctrlplane-worker
    image: cosmtrek/air
    environment:
      SERVICE_NAME: worker::webhooks
    env_file:
      - ./.env
    volumes:
      - ./deploy/air/worker.toml:/worker/.air.toml
      - ./:/worker/
      - ctrlplane-worker-go-pkg-mod:/root/go/pkg/mod # TODO: not working, fix this
      - ctrlplane-worker-build-cache:/root/.cache/go-build # TODO: not working, fix this
    working_dir: /worker


volumes:
  temporal-pg-data: {}
  ctrlplane-db-data: {}
  ctrlplane-api-go-pkg-mod: {}
  ctrlplane-api-build-cache: {}
  ctrlplane-worker-go-pkg-mod: {}
  ctrlplane-worker-build-cache: {}
