root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
args_bin = []
bin = "./tmp/quantm"
cmd = "go build -gcflags=\"-m=2 -l=0\" -o ./tmp/quantm ./cmd/quantm"
delay = 1000
exclude_dir = ["assets", "tmp", "vendor", "testdata"]
exclude_file = []
exclude_regex = ["_test.go"]
exclude_unchanged = false
follow_symlink = false
full_bin = ""
include_dir = ["internal", "cmd/quantm"]
include_ext = ["go", "tpl", "tmpl", "html"]
kill_delay = "0s"
log = "jobs-migrate-build.log"
send_interrupt = false
stop_on_error = true

[color]
app = ""
build = "yellow"
main = "magenta"
runner = "green"
watcher = "cyan"

[log]
time = false

[misc]
clean_on_exit = false

[screen]
clear_on_rebuild = false
