# Copyright © 2022, Breu Inc. <info@breu.io>. All rights reserved. 
#
# This software is made available by Breu, Inc., under the terms of the Breu  
# Community License Agreement, Version 1.0 located at  
# http://www.breu.io/breu-community-license/v1. BY INSTALLING, DOWNLOADING,  
# ACCESSING, USING OR DISTRIBUTING ANY OF THE SOFTWARE, YOU AGREE TO THE TERMS  
# OF SUCH LICENSE AGREEMENT. 

 

# This is an example of taskctl tasks configuration file.
# More information at https://github.com/taskctl/taskctl
pipelines:
  dev:
    - task: api
    - task: mothership

tasks:
  docker:
    description: Run docker with docker-compose
    command: docker-compose up --build --force-recreate
  api:
    description: Run the API server
    command: go run ./cmd/api/main.go
  worker:
    description: Run the Temporal Worker
    command: go run ./cmd/mothership/main.go

watchers:
  go:
    watch: ["**/*.go"]
    events: [create, write, remove, rename, chmod]
    task: api
