components:
  schemas:
    Stack:
      type: object
      properties:
        id:
          type: string
          format: uuid
        team_id:
          type: string
          format: uuid
        name:
          type: string
        slug:
          type: string
          format: slug
        config:
          $ref: '#/components/schemas/StackConfig'
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time

    StackConfig:
      type: object
      additionalProperties: true

    User:
      type: object
      properties:
        id:
          type: string
          format: uuid
        team_id:
          type: string
          format: uuid
          description: A user can belong to many teams. This value represents the default team for the user.
        email:
          type: string
          format: email
        first_name:
          type: string
        last_name:
          type: string
        is_verified:
          type: boolean
        is_active:
          type: boolean
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time

    Team:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        slug:
          type: string
          format: slug
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time

    GithubRepo:
      type: object
      properties:
        id:
          type: string
          format: uuid
        github_id:
          type: string
        team_id:
          type: string
          format: uuid
        name:
          type: string
        full_name:
          type: string
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
