# Copyright © 2022, Breu Inc. <info@breu.io>. All rights reserved. 
#
# This software is made available by Breu, Inc., under the terms of the Breu  
# Community License Agreement, Version 1.0 located at  
# http://www.breu.io/breu-community-license/v1. BY INSTALLING, DOWNLOADING,  
# ACCESSING, USING OR DISTRIBUTING ANY OF THE SOFTWARE, YOU AGREE TO THE TERMS  
# OF SUCH LICENSE AGREEMENT. 

version: v0.7.1-alpha.1

dsn: memory

log:
  level: debug
  format: text
  leak_sensitive_values: true

serve:
  public:
    base_url: https://auth.breu.ngrok.io/
    cors:
      enabled: true
      allowed_origins:
        - https://breu.ngrok.io
        - https://*.breu.ngrok.io
      allowed_methods:
        - POST
        - GET
        - PUT
        - PATCH
        - DELETE
      allowed_headers:
        - Authorization
        - Cookie
        - Content-Type
      exposed_headers:
        - Content-Type
        - Set-Cookie
  admin:
    base_url: http://127.0.0.1:4434/

cookies:
  domain: breu.ngrok.io
  path: /
  same_site: Lax

session:
  cookie:
    # Overrides cookies.domain for session cookies
    domain: breu.ngrok.io

    # Overrides cookies.path for session cookies
    path: /

    # Overrides cookies.samesite for session cookies
    same_site: Lax

identity:
  default_schema_id: user
  schemas:
    - id: user
      url: file:///etc/config/kratos/schemas/user.json

selfservice:
  default_browser_return_url: https://ui.breu.ngrok.io/
  allowed_return_urls:
    - https://ui.breu.ngrok.io/

  methods:
    password:
      enabled: true
    oidc:
      config:
        # secrets will be provided via environment variables
        providers:
          - id: github-core
            provider: github-core
            mapper_url: file:///etc/config/kratos/schemas/oidc.github.jsonnet
      enabled: true

  flows:
    error:
      ui_url: https://ui.breu.ngrok.io/error

    settings:
      ui_url: https://ui.breu.ngrok.io/settings
      privileged_session_max_age: 15m

    recovery:
      enabled: true
      ui_url: https://ui.breu.ngrok.io/recovery

    verification:
      enabled: true
      ui_url: https://ui.breu.ngrok.io/verification
      after:
        default_browser_return_url: https://ui.breu.ngrok.io/

    logout:
      after:
        default_browser_return_url: https://ui.breu.ngrok.io/login

    login:
      ui_url: https://ui.breu.ngrok.io/login
      lifespan: 10m

    registration:
      lifespan: 10m
      ui_url: https://ui.breu.ngrok.io/registration
      after:
        password:
          hooks:
            - hook: session
        oidc:
          hooks:
            - hook: session

# secrets:
#   cookie:
#     - PLEASE-CHANGE-ME-I-AM-VERY-INSECURE
#   cipher:
#     - 32-LONG-SECRET-NOT-SECURE-AT-ALL

# ciphers:
#   algorithm: xchacha20-poly1305

# hashers:
#   algorithm: bcrypt
#   bcrypt:
#     cost: 8

courier:
  smtp:
    connection_uri: smtps://test:test@mailslurper:1025/?skip_ssl_verify=true
