package: defs
generate:
  models: true
  echo-server: true
import-mapping:
  "../../shared/v1/schema.yaml": go.breu.io/quantm/internal/shared
  "../../auth/v1/schema.yaml": go.breu.io/quantm/internal/auth
compatibility:
  always-prefix-enum-values: true
output: defs/openapi.gen.go
output-options:
  skip-prune: true
  user-templates-dir: ../../shared/templates
