paths:
  /providers/github/webhook:
    post:
      summary: Webhook reciever for github
      description: |
        Webhook reciever for github.
        TODO: implement openapi generator.
      operationId: github-webhook
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WorkflowResponse'
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WorkflowResponse'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '../../shared/openapi.spec.yaml#/components/schemas/APIError'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '../../shared/openapi.spec.yaml#/components/schemas/APIError'

  /providers/github/complete-installation:
    post:
      summary: Complete GitHub App installation
      description: Complete GitHub App installation
      operationId: github-complete-installation
      security:
        - BearerAuth: []
        - APIKeyAuth: []
      tags:
        - providers
        - github
      requestBody:
        description: GitHub App installation
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CompleteInstallationRequest'
      responses:
        '200':
          description: GitHub App installation completed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WorkflowResponse'
        '201':
          description: GitHub App installation completed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WorkflowResponse'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '../../shared/openapi.spec.yaml#/components/schemas/APIError'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '../../shared/openapi.spec.yaml#/components/schemas/APIError'

  /providers/github/repos:
    get:
      summary: Get GitHub repositories
      description: List all the github repositories registered with ctrlplane
      operationId: github-get-repos
      security:
        - BearerAuth: []
        - APIKeyAuth: []
      tags:
        - providers
        - github
      responses:
        '200':
          description: GitHub repositories
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/GithubRepo'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '../../shared/openapi.spec.yaml#/components/schemas/APIError'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '../../shared/openapi.spec.yaml#/components/schemas/APIError'
  
  /providers/github/installations:
    get:
      summary: Get GitHub installations
      description: List all the github installations registered with ctrlplane
      operationId: github-get-installations
      security:
        - BearerAuth: []
        - APIKeyAuth: []
      tags:
        - providers
        - github
      responses:
        '200':
          description: GitHub installations
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/GithubInstallation'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '../../shared/openapi.spec.yaml#/components/schemas/APIError'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '../../shared/openapi.spec.yaml#/components/schemas/APIError'

components:
  securitySchemes:
    BearerAuth:
      $ref: '../../shared/openapi.spec.yaml#/components/securitySchemes/BearerAuth'
    APIKeyAuth:
      $ref: '../../shared/openapi.spec.yaml#/components/securitySchemes/APIKeyAuth'

  schemas:
    GithubRepo:
      type: object
      x-go-name: Repo
      x-breu-entity: github_repos
      properties:
        id:
          type: string
          format: uuid
          x-go-name: ID
          x-go-type: gocql.UUID
        github_id:
          type: integer
          format: int64
          x-go-name: GithubID
        team_id:
          type: string
          format: uuid
          x-go-name: TeamID
          x-go-type: gocql.UUID
        installation_id:
          type: integer
          format: int64
          x-go-name: InstallationID
        name:
          type: string
        full_name:
          type: string
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
      required:
        - id
        - github_id
        - team_id
        - installation_id
        - name
        - full_name
        - created_at
        - updated_at

    GithubInstallation:
      type: object
      x-go-name: Installation
      x-breu-entity: github_installations
      properties:
        id:
          type: string
          format: uuid
          x-go-name: ID
          x-go-type: gocql.UUID
        team_id:
          type: string
          format: uuid
          x-go-name: TeamID
          x-go-type: gocql.UUID
        installation_id:
          type: integer
          format: int64
          x-go-name: InstallationID
          x-oapi-codegen-extra-tags:
            validate: required,db_unique
        installation_login:
          type: string
        installation_type:
          type: string
        sender_id:
          type: integer
          format: int64
          x-go-name: SenderID
        sender_login:
          type: string
        status:
          type: string
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
      required:
        - id
        - team_id
        - installation_id
        - installation_login
        - installation_type
        - sender_id
        - sender_login
        - status
        - created_at
        - updated_at
  
    CompleteInstallationRequest:
      type: object
      description: complete the installation given the installation_id & setup_action
      properties:
        installation_id:
          type: integer
          format: int64
        setup_action:
          $ref: '#/components/schemas/SetupAction'
      required:
        - installation_id
        - setup_action

    SetupAction:
      type: string
      enum:
        - created
        - updated
        - deleted

    WorkflowResponse:
      type: object
      description: workflow status & run id
      properties:
        run_id:
          type: string
          x-go-name: RunID
        status:
          $ref: '#/components/schemas/WorkflowStatus'
      required:
        - run_id
        - status

    WorkflowStatus:
      type: string
      description: the workflow status
      enum:
        - success
        - failure
        - queued
        - signaled
        - skipped
