openapi: 3.1.0
info:
  title: Authentication API
  version: "0.0.1"
paths:
  /auth/register:
    post:
      summary: Register a new user
      description: Register a new user
      operationId: register
      security:
        - BearerAuth: []
        - APIKeyAuth: []
      tags:
        - auth
      requestBody:
        description: User to register
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterationRequest'
      responses:
        '201':
          description: User created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RegisterationResponse'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /auth/login:
    post:
      summary: Login
      description: Login
      operationId: login
      tags:
        - auth
      requestBody:
        description: Login request
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
            required:
              - email
              - password
              - confirm_password
      responses:
        '200':
          description: Login response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenResponse'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
    APIKeyAuth:
      type: apiKey
      in: header
      name: X-API-KEY

  schemas:
    RegisterationRequest:
      type: object
      properties:
        email:
          type: string
          format: email
        password:
          type: string
          format: password
        confirm_password:
          type: string
          format: password
        first_name:
          type: string
        last_name:
          type: string
        team_name:
          type: string

    RegisterationResponse:
      type: object
      properties:
        user:
          $ref: '#/components/schemas/User'
        team:
          $ref: '#/components/schemas/Team'

    User:
      type: object
      properties:
        id:
          type: string
          format: uuid
        team_id:
          type: string
          format: uuid
          description: A user can belong to many teams. This value represents the default team for the user.
        email:
          type: string
          format: email
        first_name:
          type: string
        last_name:
          type: string
        is_verified:
          type: boolean
        is_active:
          type: boolean
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time

    Team:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        slug:
          type: string
          format: slug
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time

    LoginRequest:
      type: object
      properties:
        email:
          type: string
          format: email
        password:
          type: string
          format: password

    TokenResponse:
      type: object
      properties:
        access_token:
          type: string
        refresh_token:
          type: string

    ErrorResponse:
      type: object
      properties:
        message:
          type: string
        code:
          type: integer
          format:
