package: slack
generate:
  models: true
  echo-server: true
  client: true
import-mapping:
  "../../shared/v1/schema.yaml": go.breu.io/quantm/internal/shared
  "../../core/v1/components.yaml": go.breu.io/quantm/internal/core/defs
compatibility:
  always-prefix-enum-values: true
output: openapi.gen.go
output-options:
  skip-prune: true
  user-templates-dir: ../../shared/templates
