openapi: 3.0.0
info:
  title: slack
  version: 0.0.1

paths:
  /v1/slack/notification:
    get:
      summary: |
        sends a early warning notification to channel
      description: sends a early warning notification to channel
      operationId: sendNotificationToChannel
      tags:
        - slack
      security:
        - BearerAuth: []
        - APIKeyAuth: []
      parameters:
        - name: channelID
          in: query
          description: The ID of the Slack channel to send the notification to.
          required: true
          schema:
            type: string
      responses:
        '200':
          description: send slack notification to user successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SlackNotification'
        '400':
          $ref: '../../shared/openapi.spec.yaml#/components/responses/BadRequest'
        '500':
          $ref: '../../shared/openapi.spec.yaml#/components/responses/InternalServerError'

  /v1/auth/slack/login:
    get:
      summary: Initiate slack login
      description: Slack
      operationId: login
      tags:
        - slack
      responses:
        '302':
          description: Redirects to slack login
        '400':
          $ref: '../../shared/openapi.spec.yaml#/components/responses/BadRequest'
        '500':
          $ref: '../../shared/openapi.spec.yaml#/components/responses/InternalServerError'

  /v1/auth/slack/login/callback:
    get:
      summary: Callback after Slack login
      description: Slack Oauth Redirect
      operationId: slack-oauth

      tags:
        - slack
      parameters:
        - in: query
          name: code
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SlackResponse'
        '400':
          $ref: '../../shared/openapi.spec.yaml#/components/responses/BadRequest'
        '500':
          $ref: '../../shared/openapi.spec.yaml#/components/responses/InternalServerError'

components:
  schemas:
    SlackNotification:
      type: object
      properties:
        message:
          type: string
          description: The message content to send to the Slack channel.
        channelID:
          type: string
          description: The ID of the Slack channel where the message will be sent.
      required:
        - message
        - channelID

    SlackResponse:
      type: object
      properties:
        status:
          $ref: '#/components/schemas/SlackStatus'
        errors:
          type: object
          additionalProperties:
            type: string

      required:
        - status

    SlackStatus:
      type: string
      enum:
        - Ok
        - Error
