paths:
  /core/stacks:
    post:
      summary: Create stack
      description: Create stack
      operationId: create-stack
      security:
        - BearerAuth: []
        - APIKeyAuth: []
      tags:
        - core
      requestBody:
        description: Stack
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/StackCreateRequest'
      responses:
        '201':
          description: OK
          content:
            application/json:
              schema:
                $ref: '../entity/openapi.spec.yaml#/components/schemas/Stack'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '../shared/openapi.spec.yaml#/components/schemas/APIErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '../shared/openapi.spec.yaml#/components/schemas/APIErrorResponse'
    get:
      summary: List stacks
      description: List stacks
      operationId: list-stacks
      security:
        - BearerAuth: []
        - APIKeyAuth: []
      tags:
        - core
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StackListResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '../shared/openapi.spec.yaml#/components/schemas/APIErrorResponse'

  /core/stacks/{slug}:
    get:
      summary: Get stack
      description: Get stack
      operationId: get-stack
      security:
        - BearerAuth: []
        - APIKeyAuth: []
      tags:
        - core
      parameters:
        - name: slug
          in: path
          description: Stack slug
          required: true
          schema:
            type: string
            format: slug
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '../entity/openapi.spec.yaml#/components/schemas/Stack'
        '404':
          description: Not found
          content:
            application/json:
              schema:
                $ref: '../shared/openapi.spec.yaml#/components/schemas/APIErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '../shared/openapi.spec.yaml#/components/schemas/APIErrorResponse'

components:
  securitySchemes:
    BearerAuth:
      $ref: '../shared/openapi.spec.yaml#/components/securitySchemes/BearerAuth'
    APIKeyAuth:
      $ref: '../shared/openapi.spec.yaml#/components/securitySchemes/APIKeyAuth'

  schemas:
    StackCreateRequest:
      type: object
      properties:
        name:
          type: string
        config:
          $ref: '../entity/openapi.spec.yaml#/components/schemas/StackConfig'
      required:
        - name
        - config

    StackListResponse:
      type: array
      items:
        $ref: '../entity/openapi.spec.yaml#/components/schemas/Stack'
