package: core
generate:
  models: true
  echo-server: true
  client: true
import-mapping:
  "../shared/openapi.spec.yaml": go.breu.io/quantm/internal/shared
compatibility:
  always-prefix-enum-values: true
output: openapi.gen.go
output-options:
  user-templates-dir: ../shared/templates
