root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
args_bin = []
bin = "./tmp/api"
# cmd = "go list -f '{{if not .Standard}}{{.ImportPath}}{{end}}' -deps ./cmd/api  | paste -sd, - > pkgs.txt && go build -cover -coverpkg=`cat pkgs.txt` -gcflags=\"-m=2 -l=0\" -o ./tmp/api ./cmd/api"
cmd = "go build -coverpkg=go.breu.io/quantum -gcflags=\"-m=2 -l=0\" -o ./tmp/api ./cmd/api"
delay = 1000
exclude_dir = ["assets", "tmp", "vendor", "testdata"]
exclude_file = []
exclude_regex = ["_test.go"]
exclude_unchanged = false
follow_symlink = false
full_bin = ""
include_dir = ["internal", "cmd/api"]
include_ext = ["go", "tpl", "tmpl", "html"]
kill_delay = "2s"
log = "api-build.log"
send_interrupt = true
stop_on_error = true

[color]
app = ""
build = "yellow"
main = "magenta"
runner = "green"
watcher = "cyan"

[log]
time = false

[misc]
clean_on_exit = false

[screen]
clear_on_rebuild = false
