name: mdbook
on:
  - push
jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install PageCrypt
        run: npm install -g pagecrypt
      - name: Install mdbook
        run: |
          mkdir mdbook
          curl -sSL https://github.com/rust-lang/mdBook/releases/download/v0.4.21/mdbook-v0.4.21-x86_64-unknown-linux-gnu.tar.gz | tar -xz --directory=./mdbook
          echo `pwd`/mdbook >> $GITHUB_PATH
      - name: Build docs
        run: mdbook build ./docs
      - name: Password protect docs
        run: |
          for f in $(find ./docs/book -name '*.html'); do pagecrypt $f $f ctrlplane; done
