name: release
on:
  workflow_run:
    workflows: [build]
    types:
      - completed

jobs:
  release:
    runs-on: ubuntu-20.04
    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - uses: actions/checkout@v4
        with:
          repository: quantmHQ/infra

      - id: vars
        run: echo "short_sha=$(git rev-parse --short HEAD)" >> $GITHUB_SHORT_SHA
